[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
# https://rustwiki.org/zh-CN/rust-by-example/custom_types/enum/c_like.html
[dependencies]
reqwest = { version = "0.11.11", features = ["json", "cookies"] }
tokio = { version = "1", features = ["full"] }
regex="1.8.3"
